version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-ndk-r17b
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4080m"'
	## Cache
  gradle_key: &gradle_key
    jars-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  apk_certified_key: &apk_certified_key
    apk-certified-v1-{{ .Environment.CIRCLE_WORKFLOW_ID }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  restore_apk_certified_cache: &restore_apk_certified_cache
    restore_cache:
      key: *apk_certified_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  save_apk_certified_cache: &save_apk_certified_cache
    save_cache:
      key: *apk_certified_key
      environment:
        WORKSPACE: *workspace
      paths:
        - $WORKSPACE/app/build/outputs/apk/release/appCertified.apk
      destination:
        - $WORKSPACE/release/appCertified.apk
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
		validate_running: &validate_running
		run:
		  name: Validate running
		  command: source ci/scripts/validate_running.sh
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-23;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-23;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ./gradlew :mytaxi:connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
